### ISSUE TITLE
Rise the Package Laravel Version

### ISSUE THREAD

**Issue by Yazeed-Obaid** [BRACKETS-by-TRIAD/translatable#1]
Can you rise the Laravel version in your composer.json file to be greater than 5.5.

"require": {
        "php": ">=7.0.0",
        "laravel/framework": "^5.5.*",
        "spatie/laravel-translatable": "^2.0"
    }
I want to use your package in a 5.6 Laravel application and I can't since you specified the Laravel version to be 5.5 only.

Thanks

**Comment by palypster** [comment]
We are about to release update (https://github.com/BRACKETS-by-TRIAD/craftable-installer/issues/4, https://github.com/BRACKETS-by-TRIAD/craftable/issues/20) in this PR (https://github.com/BRACKETS-by-TRIAD/craftable-installer/pull/5) this week.

**Comment by palypster** [comment]
Great news guys, Laravel 5.6 support was just introduced.
https://docs.getcraftable.com/v2/#/upgrade-guide?id=upgrade-laravel-55-gt-56

Thanks a lot for your patience.
